import React, { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import { useOutletContext } from 'react-router-dom';
import { Plus, RefreshCw, Search, Pencil, Trash2, Phone, Printer, X, Save } from 'lucide-react';

const API = `${(import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000').replace(/\/$/,'')}/api/account-profiles`;
const blank = () => ({ shop_name:'', owner_name:'', phone_1:'', phone_2:'', area:'', address:'', profile_type:'Customer', status:'active', remarks:'' });
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));

export default function AccountProfilesPage(){
  const { isRTL=false } = useOutletContext() || {};
  const [rows,setRows]=useState([]); const [loading,setLoading]=useState(true); const [search,setSearch]=useState('');
  const [open,setOpen]=useState(false); const [editId,setEditId]=useState(null); const [form,setForm]=useState(blank()); const [msg,setMsg]=useState('');
  const T = isRTL ? {
    title:'اکاؤنٹ پروفائلز',sub:'شاپس / کسٹمرز کی مکمل پروفائل ڈائریکٹری',add:'نیا پروفائل',refresh:'ریفریش',search:'شاپ، مالک، فون، ایریا یا ٹائپ تلاش کریں...',
    shop:'شاپ کا نام',owner:'مالک کا نام',p1:'فون نمبر 1',p2:'فون نمبر 2',area:'ایریا',address:'ایڈریس',type:'ٹائپ',status:'اسٹیٹس',remarks:'ریمارکس',actions:'عمل',active:'فعال',inactive:'غیر فعال',save:'محفوظ کریں',cancel:'منسوخ',print:'پرنٹ پروفائلز',no:'کوئی پروفائل نہیں ملا'
  } : {title:'Account Profiles',sub:'Shop / customer profile directory',add:'Add Profile',refresh:'Refresh',search:'Search shop, owner, phone, area or type...',shop:'Shop Name',owner:'Owner Name',p1:'Phone No 1',p2:'Phone No 2',area:'Area',address:'Address',type:'Type',status:'Status',remarks:'Remarks',actions:'Actions',active:'Active',inactive:'Inactive',save:'Save',cancel:'Cancel',print:'Print Profiles',no:'No profiles found'};

  const load=async()=>{try{setLoading(true);const r=await axios.get(API);setRows(Array.isArray(r.data?.data)?r.data.data:[]);}catch(e){setMsg(e?.response?.data?.message||'Load failed');}finally{setLoading(false)}};
  useEffect(()=>{load();},[]);
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return rows;return rows.filter(r=>[r.shop_name,r.owner_name,r.phone_1,r.phone_2,r.area,r.address,r.profile_type,r.status,r.remarks].join(' ').toLowerCase().includes(q));},[rows,search]);
  const startAdd=()=>{setEditId(null);setForm(blank());setOpen(true)};
  const startEdit=r=>{setEditId(r.id);setForm({shop_name:r.shop_name||'',owner_name:r.owner_name||'',phone_1:r.phone_1||'',phone_2:r.phone_2||'',area:r.area||'',address:r.address||'',profile_type:r.profile_type||'Customer',status:r.status||'active',remarks:r.remarks||''});setOpen(true)};
  const save=async()=>{if(!form.shop_name.trim()){setMsg('Shop name is required');return;}try{if(editId)await axios.put(`${API}/${editId}`,form);else await axios.post(API,form);setOpen(false);setMsg(editId?'Profile updated':'Profile saved');await load();}catch(e){setMsg(e?.response?.data?.message||'Save failed')}};
  const remove=async id=>{if(!confirm(isRTL?'کیا یہ پروفائل حذف کرنا ہے؟':'Delete this profile?'))return;try{await axios.delete(`${API}/${id}`);await load();}catch(e){setMsg(e?.response?.data?.message||'Delete failed')}};
  const printProfiles=(profiles=filtered)=>{
    const list = Array.isArray(profiles) ? profiles : [profiles];
    const cards=list.map((r,i)=>`<section class="profile"><div class="top"><div><div class="number">#${i+1}</div><h2>${esc(r.shop_name)}</h2><p>${esc(r.profile_type||'-')}</p></div><span class="status ${String(r.status).toLowerCase()==='active'?'on':'off'}">${esc(String(r.status).toLowerCase()==='active'?T.active:T.inactive)}</span></div><div class="grid"><div><small>${esc(T.owner)}</small><b>${esc(r.owner_name||'-')}</b></div><div><small>${esc(T.p1)}</small><b>${esc(r.phone_1||'-')}</b></div><div><small>${esc(T.p2)}</small><b>${esc(r.phone_2||'-')}</b></div><div><small>${esc(T.area)}</small><b>${esc(r.area||'-')}</b></div><div class="wide"><small>${esc(T.address)}</small><b>${esc(r.address||'-')}</b></div><div class="wide"><small>${esc(T.remarks)}</small><b>${esc(r.remarks||'-')}</b></div></div></section>`).join('');
    const w=window.open('','_blank','width=1100,height=800'); if(!w)return;
    w.document.write(`<!doctype html><html lang="${isRTL?'ur':'en'}" dir="${isRTL?'rtl':'ltr'}"><head><meta charset="UTF-8"><title>${esc(T.title)}</title><style>*{box-sizing:border-box}body{font-family:${isRTL?'"Noto Nastaliq Urdu","Noto Naskh Arabic","Jameel Noori Nastaleeq","Segoe UI",Arial,sans-serif':'Inter,"Segoe UI",Arial,sans-serif'};margin:0;padding:24px;background:#f8fafc;color:#0f172a;line-height:${isRTL?'2':'1.45'}}.report{max-width:980px;margin:auto}.head{background:#111827;color:white;padding:20px 24px;border-radius:16px;margin-bottom:16px}.head h1{margin:0}.head p{margin:5px 0 0;color:#cbd5e1}.profile{background:white;border:1px solid #D6E0EE;border-radius:16px;padding:18px;margin:0 0 14px;break-inside:avoid}.top{display:flex;justify-content:space-between;gap:12px;border-bottom:1px solid #e2e8f0;padding-bottom:12px}.top h2{margin:2px 0;font-size:20px}.top p,.number{margin:0;color:#64748b;font-size:12px}.status{height:max-content;padding:5px 10px;border-radius:999px;font-size:11px;font-weight:800}.on{background:#dcfce7;color:#166534}.off{background:#fee2e2;color:#991b1b}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:12px}.grid div{border:1px solid #e2e8f0;border-radius:10px;padding:9px}.grid small{display:block;color:#64748b;margin-bottom:4px}.wide{grid-column:span 2}@media print{body{padding:0;background:white}.head{border-radius:0}.profile{page-break-inside:avoid}}</style></head><body><main class="report"><div class="head"><h1>Ali Cages — ${esc(T.title)}</h1><p>${esc(T.sub)} · ${new Date().toLocaleString(isRTL?'ur-PK':'en-PK')}</p></div>${cards||`<p>${esc(T.no)}</p>`}</main><script>window.onload=()=>setTimeout(()=>window.print(),250)</script></body></html>`);w.document.close();
  };
  return <div dir={isRTL?'rtl':'ltr'} className="max-w-7xl mx-auto space-y-4">
    <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black text-slate-900">{T.title}</h1><p className="text-sm text-slate-500 mt-1">{T.sub}</p></div><div className="flex flex-wrap gap-2"><button onClick={printProfiles} className="px-4 py-2 rounded-xl border border-slate-300 bg-white font-bold text-sm flex gap-2 items-center"><Printer size={16}/>{T.print}</button><button onClick={load} className="px-4 py-2 rounded-xl border border-slate-300 bg-white font-bold text-sm flex gap-2 items-center"><RefreshCw size={16}/>{T.refresh}</button><button onClick={startAdd} className="px-4 py-2 rounded-xl bg-slate-900 text-white font-bold text-sm flex gap-2 items-center"><Plus size={16}/>{T.add}</button></div></div>
    {msg&&<div className="bg-blue-50 border border-blue-200 text-blue-800 rounded-xl px-4 py-2 text-sm">{msg}</div>}
    <div className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden"><div className="p-4 border-b border-slate-200"><div className="relative max-w-lg"><Search size={16} className={`absolute top-3 text-slate-400 ${isRTL?'right-3':'left-3'}`}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={T.search} className={`w-full h-10 border border-slate-300 rounded-xl text-sm ${isRTL?'pr-10 pl-3':'pl-10 pr-3'}`}/></div></div><div className="overflow-x-auto"><table className="w-full min-w-[1450px] text-sm"><thead className="bg-slate-900 text-white text-xs uppercase"><tr><th className="p-3">#</th><th className="p-3 text-start">{T.shop}</th><th className="p-3 text-start">{T.owner}</th><th className="p-3 text-start">{T.p1}</th><th className="p-3 text-start">{T.p2}</th><th className="p-3 text-start">{T.area}</th><th className="p-3 text-start">{T.address}</th><th className="p-3 text-start">{T.type}</th><th className="p-3">{T.status}</th><th className="p-3 text-start">{T.remarks}</th><th className="p-3">{T.actions}</th></tr></thead><tbody className="divide-y divide-slate-100">{loading?<tr><td colSpan="11" className="p-10 text-center text-slate-400">Loading...</td></tr>:filtered.length===0?<tr><td colSpan="11" className="p-10 text-center text-slate-400">{T.no}</td></tr>:filtered.map((r,i)=><tr key={r.id} className="hover:bg-slate-50"><td className="p-3 text-center text-slate-400">{i+1}</td><td className="p-3 font-bold">{r.shop_name}</td><td className="p-3">{r.owner_name||'-'}</td><td className="p-3">{r.phone_1||'-'}</td><td className="p-3">{r.phone_2||'-'}</td><td className="p-3">{r.area||'-'}</td><td className="p-3 max-w-[260px]">{r.address||'-'}</td><td className="p-3">{r.profile_type||'-'}</td><td className="p-3 text-center"><span className={`px-2 py-1 rounded-full text-xs font-bold ${String(r.status).toLowerCase()==='active'?'bg-emerald-50 text-emerald-700':'bg-rose-50 text-rose-700'}`}>{String(r.status).toLowerCase()==='active'?T.active:T.inactive}</span></td><td className="p-3 max-w-[220px]">{r.remarks||'-'}</td><td className="p-3"><div className="flex justify-center gap-1"><button title="Edit" onClick={()=>startEdit(r)} className="p-2 rounded-lg bg-blue-50 text-blue-700"><Pencil size={15}/></button><button title="Delete" onClick={()=>remove(r.id)} className="p-2 rounded-lg bg-rose-50 text-rose-700"><Trash2 size={15}/></button><button title="Print profile" onClick={()=>printProfiles([r])} className="p-2 rounded-lg bg-violet-50 text-violet-700"><Printer size={15}/></button>{r.phone_1&&<a title="Call" href={`tel:${r.phone_1}`} className="px-3 py-2 rounded-lg bg-emerald-600 text-white font-bold text-xs flex items-center gap-1"><Phone size={14}/>Call</a>}</div></td></tr>)}</tbody></table></div></div>
    {open&&<div className="fixed inset-0 z-[100] bg-slate-950/50 flex items-center justify-center p-4" onMouseDown={e=>e.currentTarget===e.target&&setOpen(false)}><div className="bg-white rounded-2xl w-full max-w-3xl shadow-2xl overflow-hidden"><div className="bg-slate-900 text-white px-5 py-4 flex justify-between items-center"><h2 className="font-black">{editId?`${T.add} — #${editId}`:T.add}</h2><button onClick={()=>setOpen(false)}><X/></button></div><div className="p-5 grid grid-cols-1 md:grid-cols-2 gap-4">{[[T.shop,'shop_name'],[T.owner,'owner_name'],[T.p1,'phone_1'],[T.p2,'phone_2'],[T.area,'area'],[T.address,'address']].map(([label,key])=><label key={key} className={key==='address'?'md:col-span-2':''}><span className="block text-xs font-bold text-slate-500 mb-1">{label}{key==='shop_name'?' *':''}</span><input value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="w-full h-10 border border-slate-300 rounded-xl px-3"/></label>)}<label><span className="block text-xs font-bold text-slate-500 mb-1">{T.type}</span><input value={form.profile_type} onChange={e=>setForm({...form,profile_type:e.target.value})} className="w-full h-10 border border-slate-300 rounded-xl px-3" placeholder="Customer / Shop / Dealer"/></label><label><span className="block text-xs font-bold text-slate-500 mb-1">{T.status}</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="w-full h-10 border border-slate-300 rounded-xl px-3"><option value="active">{T.active}</option><option value="inactive">{T.inactive}</option></select></label><label className="md:col-span-2"><span className="block text-xs font-bold text-slate-500 mb-1">{T.remarks}</span><textarea rows="3" value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})} className="w-full border border-slate-300 rounded-xl px-3 py-2"/></label></div><div className="px-5 py-4 bg-slate-50 border-t flex justify-end gap-2"><button onClick={()=>setOpen(false)} className="px-4 py-2 rounded-xl border bg-white font-bold">{T.cancel}</button><button onClick={save} className="px-5 py-2 rounded-xl bg-slate-900 text-white font-bold flex gap-2 items-center"><Save size={16}/>{T.save}</button></div></div></div>}
  </div>
}
