import React,{useCallback,useEffect,useMemo,useState}from"react";
import axios from"axios";
const API=`${(import.meta.env.VITE_API_BASE_URL||"http://localhost:5000").replace(/\/$/,"")}/api`;
const today=()=>new Date().toISOString().slice(0,10);const n=v=>Number(v||0);const fmt=v=>n(v).toLocaleString("en-PK",{maximumFractionDigits:3});const money=v=>n(v).toLocaleString("en-PK",{minimumFractionDigits:2,maximumFractionDigits:2});const list=x=>Array.isArray(x)?x:x?.data||x?.records||[];
const blank=()=>({return_no:`PR-${String(Date.now()).slice(-6)}`,return_date:today(),production_invoice_id:"",warehouse:"",reason:"",items:[]});
export default function ProductionReturnInvoicePage(){
 const[rows,setRows]=useState([]),[batches,setBatches]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[show,setShow]=useState(false),[editId,setEditId]=useState(null),[form,setForm]=useState(blank()),[search,setSearch]=useState(""),[msg,setMsg]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const[a,b]=await Promise.all([axios.get(`${API}/production-returns`),axios.get(`${API}/production-returns/setup`)]);setRows(list(a.data));setBatches(list(b.data));}catch(e){setMsg(e?.response?.data?.message||e.message)}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);
 const selected=batches.find(b=>String(b.id)===String(form.production_invoice_id));
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return rows.filter(r=>!q||[r.return_no,r.batch_no,r.assignee_name,r.warehouse,...(r.items||[]).map(x=>x.product_name)].join(" ").toLowerCase().includes(q))},[rows,search]);
 const totals=useMemo(()=>form.items.reduce((a,x)=>({q:a.q+n(x.quantity),amount:a.amount+n(x.quantity)*n(x.rate)}),{q:0,amount:0}),[form.items]);
 const chooseBatch=id=>{const b=batches.find(x=>String(x.id)===String(id));setForm(f=>({...f,production_invoice_id:id,warehouse:b?.warehouse||f.warehouse,items:(b?.items||[]).filter(x=>n(x.available_qty)>0).map(x=>({production_item_id:x.id,product_id:x.product_id,product_name:x.product_name,description:x.description||"",unit_name:x.unit_name||"",produced_qty:n(x.quantity),already_returned_qty:n(x.returned_qty),available_qty:n(x.available_qty),quantity:"",rate:n(x.rate)}))}))};
 const openNew=()=>{setEditId(null);setForm(blank());setShow(true);setMsg("")};
 const openEdit=r=>{setEditId(r.id);const batch=batches.find(b=>String(b.id)===String(r.production_invoice_id));const existing=new Map((r.items||[]).map(x=>[String(x.production_item_id),x]));const items=(batch?.items||[]).map(x=>{const old=existing.get(String(x.id));return{production_item_id:x.id,product_id:x.product_id,product_name:x.product_name,description:x.description||"",unit_name:x.unit_name||"",produced_qty:n(x.quantity),already_returned_qty:Math.max(n(x.returned_qty)-n(old?.quantity),0),available_qty:n(x.available_qty)+n(old?.quantity),quantity:old?.quantity||"",rate:n(x.rate)}}).filter(x=>x.quantity||x.available_qty>0);setForm({return_no:r.return_no||"",return_date:String(r.return_date||today()).slice(0,10),production_invoice_id:r.production_invoice_id||"",warehouse:r.warehouse||batch?.warehouse||"",reason:r.reason||"",items});setShow(true);setMsg("")};
 const updateQty=(i,v)=>setForm(f=>({...f,items:f.items.map((x,k)=>k===i?{...x,quantity:v}:x)}));
 const save=async()=>{if(!form.production_invoice_id)return setMsg("Select original production batch.");const items=form.items.filter(x=>n(x.quantity)>0);if(!items.length)return setMsg("Enter return quantity for at least one product.");const bad=items.find(x=>n(x.quantity)>n(x.available_qty));if(bad)return setMsg(`${bad.product_name}: return qty cannot exceed ${fmt(bad.available_qty)}.`);setSaving(true);setMsg("");try{const payload={...form,items};if(editId)await axios.put(`${API}/production-returns/${editId}`,payload);else await axios.post(`${API}/production-returns`,payload);setShow(false);await load()}catch(e){setMsg(e?.response?.data?.message||e.message)}finally{setSaving(false)}};
 const del=async id=>{if(!window.confirm("Delete this production return?"))return;try{await axios.delete(`${API}/production-returns/${id}`);load()}catch(e){setMsg(e?.response?.data?.message||e.message)}};
 const inp="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-rose-400 focus:ring-2 focus:ring-rose-100";
 return <div className="min-h-screen bg-slate-50 p-3 sm:p-5 lg:p-7"><div className="mx-auto max-w-7xl space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-extrabold text-slate-900">Production Return</h1><p className="text-sm text-slate-500">Return finished production against the original batch with item-level quantity control.</p></div><button onClick={openNew} className="rounded-xl bg-rose-600 px-5 py-2.5 text-sm font-bold text-white">+ New Production Return</button></div>{msg&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{msg}</div>}<div className="rounded-2xl border border-slate-200 bg-white p-4"><input className={`${inp} max-w-xl`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search return no, batch, product, assignee..."/></div>
 <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-[980px] w-full text-sm"><thead className="bg-slate-950 text-white"><tr>{["#","Return No","Return Date","Batch No","Assigned To","Products","Warehouse","Return Qty","Return Amount","Actions"].map(x=><th key={x} className="px-3 py-3 text-left text-[11px] uppercase">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan="10" className="p-10 text-center">Loading...</td></tr>:filtered.length===0?<tr><td colSpan="10" className="p-10 text-center text-slate-400">No production returns found.</td></tr>:filtered.map((r,i)=><tr key={r.id} className="border-b border-slate-100"><td className="px-3 py-3">{i+1}</td><td className="px-3 py-3 font-bold text-rose-700">{r.return_no}</td><td className="px-3 py-3">{String(r.return_date||"").slice(0,10)}</td><td className="px-3 py-3">{r.batch_no||"—"}</td><td className="px-3 py-3">{r.assignee_name||"—"}</td><td className="px-3 py-3">{(r.items||[]).map(x=>x.product_name).filter(Boolean).join(", ")||r.product||"—"}</td><td className="px-3 py-3">{r.warehouse||"—"}</td><td className="px-3 py-3 text-right font-bold">{fmt(r.total_qty||r.quantity_returned)}</td><td className="px-3 py-3 text-right font-bold">Rs {money(r.total_amount)}</td><td className="px-3 py-3"><div className="flex gap-2"><button onClick={()=>openEdit(r)} className="rounded-lg bg-indigo-50 px-3 py-1.5 text-xs font-bold text-indigo-700">Edit</button><button onClick={()=>del(r.id)} className="rounded-lg bg-rose-50 px-3 py-1.5 text-xs font-bold text-rose-700">Delete</button></div></td></tr>)}</tbody></table></div></div>
 {show&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-3 sm:p-6"><div className="mx-auto my-4 max-w-6xl rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-4 sm:p-5"><div><h2 className="text-xl font-extrabold">{editId?"Edit":"New"} Production Return</h2><p className="text-xs text-slate-500">Choose original production batch; only available quantities can be returned.</p></div><button onClick={()=>setShow(false)} className="rounded-lg bg-slate-100 px-3 py-2">✕</button></div><div className="space-y-5 p-4 sm:p-5"><div className="grid grid-cols-1 gap-3 md:grid-cols-4"><label className="text-xs font-bold">Return No *<input className={`${inp} mt-1 font-normal`} value={form.return_no} onChange={e=>setForm(f=>({...f,return_no:e.target.value}))}/></label><label className="text-xs font-bold">Return Date *<input type="date" className={`${inp} mt-1 font-normal`} value={form.return_date} onChange={e=>setForm(f=>({...f,return_date:e.target.value}))}/></label><label className="text-xs font-bold md:col-span-2">Original Production Batch *<select disabled={!!editId} className={`${inp} mt-1 font-normal disabled:bg-slate-100`} value={form.production_invoice_id} onChange={e=>chooseBatch(e.target.value)}><option value="">Select Batch</option>{batches.map(b=><option key={b.id} value={b.id}>{b.batch_no} — {String(b.production_date||"").slice(0,10)} — {b.assignee_name||b.supervisor||"Unassigned"}</option>)}</select></label><label className="text-xs font-bold md:col-span-2">Assigned To<div className="mt-1 h-10 rounded-xl bg-slate-100 px-3 py-2.5 font-normal">{selected?.assignee_name||selected?.supervisor||"—"}</div></label><label className="text-xs font-bold md:col-span-2">Warehouse<input className={`${inp} mt-1 font-normal`} value={form.warehouse} onChange={e=>setForm(f=>({...f,warehouse:e.target.value}))}/></label></div>
 <div className="overflow-hidden rounded-2xl border border-slate-200"><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-xs"><thead className="bg-slate-100"><tr>{["#","Product","Description","Unit","Produced","Already Returned","Available","Return Qty","Rate","Amount"].map(x=><th key={x} className="px-2 py-2 text-left">{x}</th>)}</tr></thead><tbody>{form.items.length===0?<tr><td colSpan="10" className="p-8 text-center text-slate-400">Select a production batch.</td></tr>:form.items.map((x,i)=><tr key={x.production_item_id} className="border-t"><td className="px-2 py-2">{i+1}</td><td className="px-2 py-2 font-bold">{x.product_name}</td><td className="px-2 py-2">{x.description||"—"}</td><td className="px-2 py-2">{x.unit_name||"—"}</td><td className="px-2 py-2 text-right">{fmt(x.produced_qty)}</td><td className="px-2 py-2 text-right">{fmt(x.already_returned_qty)}</td><td className="px-2 py-2 text-right font-bold text-emerald-700">{fmt(x.available_qty)}</td><td className="px-2 py-2"><input type="number" min="0" max={x.available_qty} step="0.001" className={`${inp} text-right`} value={x.quantity} onChange={e=>updateQty(i,e.target.value)}/></td><td className="px-2 py-2 text-right">{money(x.rate)}</td><td className="px-2 py-2 text-right font-bold">{money(n(x.quantity)*n(x.rate))}</td></tr>)}</tbody><tfoot className="bg-slate-50 font-bold"><tr><td colSpan="7" className="px-2 py-3 text-right">TOTAL RETURN</td><td className="px-2 py-3 text-right">{fmt(totals.q)}</td><td></td><td className="px-2 py-3 text-right">Rs {money(totals.amount)}</td></tr></tfoot></table></div></div><label className="block text-xs font-bold">Reason / Remarks<textarea rows="3" className="mt-1 w-full rounded-xl border border-slate-200 p-3 text-sm font-normal" value={form.reason} onChange={e=>setForm(f=>({...f,reason:e.target.value}))}/></label></div><div className="flex flex-col-reverse gap-2 border-t p-4 sm:flex-row sm:justify-end"><button onClick={()=>setShow(false)} className="rounded-xl border px-5 py-2.5 text-sm font-bold">Cancel</button><button disabled={saving} onClick={save} className="rounded-xl bg-rose-600 px-6 py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving?"Saving...":"Save Return"}</button></div></div></div>}
 </div></div>;
}
