import React,{useCallback,useEffect,useMemo,useState}from"react";
import axios from"axios";
const API=`${(import.meta.env.VITE_API_BASE_URL||"http://localhost:5000").replace(/\/$/,"")}/api`;
const today=()=>new Date().toISOString().slice(0,10);const n=v=>Number(v||0);const money=v=>n(v).toLocaleString("en-PK",{minimumFractionDigits:2,maximumFractionDigits:2});const qty=v=>n(v).toLocaleString("en-PK",{maximumFractionDigits:3});
const emptyItem=()=>({product_id:"",product_name:"",description:"",product_type_id:"",type_name:"",category_id:"",category_name:"",unit_id:"",unit_name:"",quantity:"",rate:"",amount:0});
const blank=()=>({batch_no:`PROD-${String(Date.now()).slice(-6)}`,production_date:today(),assignee_type:"employee",assignee_id:"",assignee_name:"",warehouse:"",remarks:"",status:"Pending",items:[emptyItem()]});
const list=x=>Array.isArray(x)?x:x?.data||x?.records||[];
export default function ProductionInvoicePage(){
 const[rows,setRows]=useState([]),[setup,setSetup]=useState({products:[],employees:[],contractors:[]}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[search,setSearch]=useState(""),[show,setShow]=useState(false),[editId,setEditId]=useState(null),[form,setForm]=useState(blank()),[msg,setMsg]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const[a,b]=await Promise.all([axios.get(`${API}/production-invoices`),axios.get(`${API}/production-invoices/setup`)]);setRows(list(a.data));setSetup(b.data?.data||{products:[],employees:[],contractors:[]});}catch(e){setMsg(e?.response?.data?.message||e.message)}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);
 const assignees=form.assignee_type==="contractor"?setup.contractors:setup.employees;const selectedAssignee=assignees.find(x=>String(x.id)===String(form.assignee_id));
 const totals=useMemo(()=>form.items.reduce((a,x)=>({q:a.q+n(x.quantity),amount:a.amount+n(x.quantity)*n(x.rate)}),{q:0,amount:0}),[form.items]);
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return rows.filter(r=>!q||[r.batch_no,r.production_date,r.assignee_name,r.warehouse,r.status,...(r.items||[]).map(x=>x.product_name)].join(" ").toLowerCase().includes(q))},[rows,search]);
 const openNew=()=>{setEditId(null);setForm(blank());setShow(true);setMsg("")};
 const openEdit=r=>{setEditId(r.id);setForm({batch_no:r.batch_no||"",production_date:String(r.production_date||today()).slice(0,10),assignee_type:r.assignee_type||"employee",assignee_id:r.assignee_id||"",assignee_name:r.assignee_name||r.supervisor||"",warehouse:r.warehouse||"",remarks:r.remarks||"",status:r.status||"Pending",items:(r.items?.length?r.items:[{product_id:r.product_id,product_name:r.product,quantity:r.quantity_produced,rate:0}]).map(x=>({...emptyItem(),...x,quantity:x.quantity??x.quantity_produced??"",rate:x.rate??0}))});setShow(true);setMsg("")};
 const updateItem=(i,patch)=>setForm(f=>({...f,items:f.items.map((x,k)=>k===i?{...x,...patch}:x)}));
 const selectProduct=(i,id)=>{const p=setup.products.find(x=>String(x.id)===String(id));if(!p)return updateItem(i,{product_id:"",product_name:"",type_name:"",category_name:"",unit_name:""});updateItem(i,{product_id:p.id,product_name:p.product_name,product_type_id:p.product_type_id||"",type_name:p.type_name||"",category_id:p.category_id||"",category_name:p.category_name||"",unit_id:p.unit_id||"",unit_name:p.unit_name||""})};
 const selectAssignee=id=>{const a=assignees.find(x=>String(x.id)===String(id));const rate=n(a?.default_rate);setForm(f=>({...f,assignee_id:id,assignee_name:a?.name||"",items:f.items.map(x=>({...x,rate:rate||x.rate}))}))};
 const save=async()=>{if(!form.batch_no||!form.production_date)return setMsg("Batch No and date are required.");const items=form.items.filter(x=>x.product_id&&n(x.quantity)>0);if(!items.length)return setMsg("Add at least one product with quantity.");setSaving(true);setMsg("");try{const payload={...form,items};if(editId)await axios.put(`${API}/production-invoices/${editId}`,payload);else await axios.post(`${API}/production-invoices`,payload);setShow(false);await load()}catch(e){setMsg(e?.response?.data?.message||e.message)}finally{setSaving(false)}};
 const del=async id=>{if(!window.confirm("Delete this production invoice?"))return;try{await axios.delete(`${API}/production-invoices/${id}`);load()}catch(e){setMsg(e?.response?.data?.message||e.message)}};
 const printInvoice=r=>{const body=(r.items||[]).map((x,i)=>`<tr><td>${i+1}</td><td>${x.product_name||""}</td><td>${x.description||""}</td><td>${x.type_name||""}</td><td>${x.category_name||""}</td><td>${x.unit_name||""}</td><td class="n">${qty(x.quantity)}</td><td class="n">${money(x.rate)}</td><td class="n">${money(x.amount)}</td></tr>`).join("");const w=window.open("","_blank");if(!w)return;w.document.write(`<!doctype html><html><head><title>${r.batch_no}</title><style>body{font-family:Arial;padding:24px;color:#111827}.head{display:flex;justify-content:space-between;border-bottom:2px solid #111827;padding-bottom:14px}.meta{margin:16px 0;display:grid;grid-template-columns:repeat(3,1fr);gap:8px}table{width:100%;border-collapse:collapse;font-size:11px}th{background:#111827;color:#fff;padding:8px;text-align:left}td{padding:8px;border-bottom:1px solid #ddd}.n{text-align:right}tfoot td{font-weight:bold;background:#f3f4f6}@page{size:A4 landscape;margin:10mm}</style></head><body><div class="head"><div><h2>Production Invoice</h2><b>${r.batch_no}</b></div><div>${String(r.production_date||"").slice(0,10)}</div></div><div class="meta"><div>Assigned To: <b>${r.assignee_name||r.supervisor||"—"}</b> (${r.assignee_type||"—"})</div><div>Warehouse: <b>${r.warehouse||"—"}</b></div><div>Status: <b>${r.status||"—"}</b></div></div><table><thead><tr><th>#</th><th>Product</th><th>Description</th><th>Type</th><th>Category</th><th>Unit</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${body}</tbody><tfoot><tr><td colspan="6">TOTAL</td><td class="n">${qty(r.total_qty)}</td><td></td><td class="n">Rs ${money(r.total_amount)}</td></tr></tfoot></table><p>${r.remarks||""}</p><script>window.onload=()=>setTimeout(()=>window.print(),200)</script></body></html>`);w.document.close()};
 const inp="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-fuchsia-400 focus:ring-2 focus:ring-fuchsia-100";
 return <div className="min-h-screen bg-slate-50 p-3 sm:p-5 lg:p-7"><div className="mx-auto max-w-7xl space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-extrabold text-slate-900">Production Invoice</h1><p className="text-sm text-slate-500">Invoice-style production batches with employee/contractor assignment and detailed products.</p></div><button onClick={openNew} className="rounded-xl bg-fuchsia-700 px-5 py-2.5 text-sm font-bold text-white">+ New Production</button></div>{msg&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{msg}</div>}
 <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search batch, product, employee/contractor, warehouse..." className={`${inp} max-w-xl`}/></div>
 <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-[1000px] w-full text-sm"><thead className="bg-slate-950 text-white"><tr>{["#","Batch No","Production Date","Assigned To","Products","Warehouse","Total Qty","Total Amount","Status","Actions"].map(x=><th key={x} className="px-3 py-3 text-left text-[11px] uppercase">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan="10" className="p-10 text-center">Loading...</td></tr>:filtered.length===0?<tr><td colSpan="10" className="p-10 text-center text-slate-400">No production invoices found.</td></tr>:filtered.map((r,i)=><tr key={r.id} className="border-b border-slate-100"><td className="px-3 py-3">{i+1}</td><td className="px-3 py-3 font-bold text-fuchsia-700">{r.batch_no}</td><td className="px-3 py-3">{String(r.production_date||"").slice(0,10)}</td><td className="px-3 py-3"><b>{r.assignee_name||r.supervisor||"—"}</b><div className="text-xs text-slate-400 capitalize">{r.assignee_type||""}</div></td><td className="px-3 py-3">{(r.items||[]).map(x=>x.product_name).filter(Boolean).join(", ")||r.product||"—"}</td><td className="px-3 py-3">{r.warehouse||"—"}</td><td className="px-3 py-3 text-right font-bold">{qty(r.total_qty||r.quantity_produced)}</td><td className="px-3 py-3 text-right font-bold">Rs {money(r.total_amount)}</td><td className="px-3 py-3">{r.status||"Pending"}</td><td className="px-3 py-3"><div className="flex gap-2"><button onClick={()=>printInvoice(r)} className="rounded-lg border px-2.5 py-1.5 text-xs">Print</button><button onClick={()=>openEdit(r)} className="rounded-lg bg-indigo-50 px-2.5 py-1.5 text-xs font-bold text-indigo-700">Edit</button><button onClick={()=>del(r.id)} className="rounded-lg bg-rose-50 px-2.5 py-1.5 text-xs font-bold text-rose-700">Delete</button></div></td></tr>)}</tbody></table></div></div>
 {show&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-3 sm:p-6"><div className="mx-auto my-3 max-w-7xl rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-4 sm:p-5"><div><h2 className="text-xl font-extrabold">{editId?"Edit":"New"} Production</h2><p className="text-xs text-slate-500">Header + product details; rate is suggested from the selected employee/contractor rate record and remains editable.</p></div><button onClick={()=>setShow(false)} className="rounded-lg bg-slate-100 px-3 py-2">✕</button></div><div className="space-y-5 p-4 sm:p-5">
 <div className="grid grid-cols-1 gap-3 md:grid-cols-4"><label className="text-xs font-bold">Batch No *<input className={`${inp} mt-1 font-normal`} value={form.batch_no} onChange={e=>setForm(f=>({...f,batch_no:e.target.value}))}/></label><label className="text-xs font-bold">Production Date *<input type="date" className={`${inp} mt-1 font-normal`} value={form.production_date} onChange={e=>setForm(f=>({...f,production_date:e.target.value}))}/></label><label className="text-xs font-bold">Assign Type<select className={`${inp} mt-1 font-normal`} value={form.assignee_type} onChange={e=>setForm(f=>({...f,assignee_type:e.target.value,assignee_id:"",assignee_name:""}))}><option value="employee">Employee</option><option value="contractor">Contractor</option></select></label><label className="text-xs font-bold">Employee / Contractor<select className={`${inp} mt-1 font-normal`} value={form.assignee_id} onChange={e=>selectAssignee(e.target.value)}><option value="">Select</option>{assignees.map(a=><option key={a.id} value={a.id}>{a.name} {n(a.default_rate)>0?`— Rate ${money(a.default_rate)}`:""}</option>)}</select></label><label className="text-xs font-bold md:col-span-2">Warehouse<input className={`${inp} mt-1 font-normal`} value={form.warehouse} onChange={e=>setForm(f=>({...f,warehouse:e.target.value}))}/></label><label className="text-xs font-bold">Status<select className={`${inp} mt-1 font-normal`} value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value}))}><option>Pending</option><option>In Progress</option><option>Completed</option><option>Closed</option></select></label><label className="text-xs font-bold">Suggested Assignee Rate<div className="mt-1 h-10 rounded-xl bg-slate-100 px-3 py-2.5 font-mono text-sm">{selectedAssignee?money(selectedAssignee.default_rate):"0.00"}</div></label></div>
 <div className="rounded-2xl border border-slate-200"><div className="flex items-center justify-between border-b px-4 py-3"><div><b>Products</b><div className="text-xs text-slate-500">Description is manual, not auto-generated from master packing.</div></div><button onClick={()=>setForm(f=>({...f,items:[...f.items,emptyItem()]}))} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">+ Add Row</button></div><div className="overflow-x-auto"><table className="min-w-[1250px] w-full text-xs"><thead className="bg-slate-100"><tr>{["#","Product *","Description","Type","Category","Unit","Qty *","Rate","Amount",""].map(x=><th key={x} className="px-2 py-2 text-left">{x}</th>)}</tr></thead><tbody>{form.items.map((x,i)=><tr key={i} className="border-t"><td className="px-2 py-2">{i+1}</td><td className="px-2 py-2"><select className={inp} value={x.product_id} onChange={e=>selectProduct(i,e.target.value)}><option value="">Select Product</option>{setup.products.map(p=><option key={p.id} value={p.id}>{p.product_name}</option>)}</select></td><td className="px-2 py-2"><input className={inp} value={x.description||""} onChange={e=>updateItem(i,{description:e.target.value})} placeholder="Manual description"/></td><td className="px-2 py-2">{x.type_name||"—"}</td><td className="px-2 py-2">{x.category_name||"—"}</td><td className="px-2 py-2">{x.unit_name||"—"}</td><td className="px-2 py-2"><input type="number" min="0" step="0.001" className={`${inp} text-right`} value={x.quantity} onChange={e=>updateItem(i,{quantity:e.target.value})}/></td><td className="px-2 py-2"><input type="number" min="0" step="0.01" className={`${inp} text-right`} value={x.rate} onChange={e=>updateItem(i,{rate:e.target.value})}/></td><td className="px-2 py-2 text-right font-bold">{money(n(x.quantity)*n(x.rate))}</td><td className="px-2 py-2"><button disabled={form.items.length===1} onClick={()=>setForm(f=>({...f,items:f.items.filter((_,k)=>k!==i)}))} className="rounded-lg bg-rose-50 px-3 py-2 text-rose-700 disabled:opacity-30">✕</button></td></tr>)}</tbody><tfoot className="bg-slate-50 font-bold"><tr><td colSpan="6" className="px-2 py-3 text-right">TOTAL</td><td className="px-2 py-3 text-right">{qty(totals.q)}</td><td></td><td className="px-2 py-3 text-right">Rs {money(totals.amount)}</td><td></td></tr></tfoot></table></div></div>
 <label className="block text-xs font-bold">Remarks<textarea rows="2" className="mt-1 w-full rounded-xl border border-slate-200 p-3 text-sm font-normal" value={form.remarks} onChange={e=>setForm(f=>({...f,remarks:e.target.value}))}/></label></div><div className="flex flex-col-reverse gap-2 border-t p-4 sm:flex-row sm:justify-end"><button onClick={()=>setShow(false)} className="rounded-xl border px-5 py-2.5 text-sm font-bold">Cancel</button><button disabled={saving} onClick={save} className="rounded-xl bg-fuchsia-700 px-6 py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving?"Saving...":"Save Production"}</button></div></div></div>}
 </div></div>;
}
