import React, { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import { useNavigate, useOutletContext } from 'react-router-dom';
import { RefreshCw, Search, CalendarDays, ShieldCheck } from 'lucide-react';

const API = `${(import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000').replace(/\/$/,'')}/api/transaction-history`;
const today = () => new Date().toISOString().slice(0,10);
const firstOfMonth=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`};

export default function TransactionHistoryPage(){
  const {isRTL=false}=useOutletContext()||{}; const nav=useNavigate();
  const user=useMemo(()=>{try{return JSON.parse(localStorage.getItem('user')||'null')}catch{return null}},[]);
  const [rows,setRows]=useState([]);const [loading,setLoading]=useState(true);const [search,setSearch]=useState('');const [from,setFrom]=useState(firstOfMonth());const [to,setTo]=useState(today());const [err,setErr]=useState('');
  const T=isRTL?{title:'ٹرانزیکشن ہسٹری',sub:'ایڈمن آڈٹ ٹریل — ہر انٹری کے ساتھ صارف، تاریخ اور وقت',txn:'ٹرانزیکشن نمبر',account:'اکاؤنٹ نام',entry:'انٹری نمبر',user:'صارف',action:'عمل',module:'ماڈیول',date:'تاریخ',time:'وقت',search:'ٹرانزیکشن، اکاؤنٹ، انٹری یا صارف تلاش کریں...',refresh:'ریفریش',no:'کوئی ٹرانزیکشن نہیں ملی'}:{title:'Transaction History',sub:'Admin audit trail with entry, user, date and time',txn:'Transaction No.',account:'Account Name',entry:'Entry No.',user:'User',action:'Action',module:'Module',date:'Date',time:'Time',search:'Search transaction, account, entry or user...',refresh:'Refresh',no:'No transactions found'};
  useEffect(()=>{if(String(user?.role||'').toLowerCase()!=='admin')nav('/app/dashboard',{replace:true});},[user,nav]);
  const load=async()=>{try{setLoading(true);setErr('');const r=await axios.get(API,{params:{from_date:from,to_date:to,search}});setRows(Array.isArray(r.data?.data)?r.data.data:[])}catch(e){setErr(e?.response?.data?.message||'Load failed')}finally{setLoading(false)}};
  useEffect(()=>{if(String(user?.role||'').toLowerCase()==='admin')load();},[from,to]);
  return <div dir={isRTL?'rtl':'ltr'} className="max-w-7xl mx-auto space-y-4"><div className="rounded-2xl bg-white border border-slate-200 shadow-sm p-5 flex flex-wrap gap-3 justify-between items-center"><div><div className="flex items-center gap-2"><ShieldCheck className="text-indigo-600"/><h1 className="text-2xl font-black text-slate-900">{T.title}</h1></div><p className="text-sm text-slate-500 mt-1">{T.sub}</p></div><button onClick={load} className="px-4 py-2 rounded-xl border border-slate-300 bg-white font-bold text-sm flex items-center gap-2"><RefreshCw size={16}/>{T.refresh}</button></div>
  {err&&<div className="bg-rose-50 border border-rose-200 text-rose-700 rounded-xl px-4 py-3 text-sm">{err}</div>}
  <div className="bg-white rounded-2xl border border-slate-200 shadow-sm"><div className="p-4 border-b border-slate-200 flex flex-wrap items-end gap-3"><label><span className="block text-[11px] font-bold text-slate-500 mb-1">From</span><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="h-10 border border-slate-300 rounded-xl px-3"/></label><label><span className="block text-[11px] font-bold text-slate-500 mb-1">To</span><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="h-10 border border-slate-300 rounded-xl px-3"/></label><div className="relative flex-1 min-w-[260px]"><Search size={16} className={`absolute top-3 text-slate-400 ${isRTL?'right-3':'left-3'}`}/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder={T.search} className={`w-full h-10 border border-slate-300 rounded-xl ${isRTL?'pr-10 pl-3':'pl-10 pr-3'}`}/></div><button onClick={load} className="h-10 px-4 rounded-xl bg-slate-900 text-white font-bold text-sm">Search</button></div>
  <div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="bg-slate-900 text-white text-xs uppercase"><tr><th className="p-3">#</th><th className="p-3 text-start">{T.txn}</th><th className="p-3 text-start">{T.account}</th><th className="p-3 text-start">{T.entry}</th><th className="p-3 text-start">{T.user}</th><th className="p-3 text-start">{T.action}</th><th className="p-3 text-start">{T.module}</th><th className="p-3 text-start">{T.date}</th><th className="p-3 text-start">{T.time}</th></tr></thead><tbody className="divide-y divide-slate-100">{loading?<tr><td colSpan="9" className="p-10 text-center text-slate-400">Loading...</td></tr>:rows.length===0?<tr><td colSpan="9" className="p-10 text-center text-slate-400">{T.no}</td></tr>:rows.map((r,i)=><tr key={r.id} className="hover:bg-slate-50"><td className="p-3 text-center text-slate-400">{i+1}</td><td className="p-3 font-mono font-bold text-indigo-700">{r.transaction_no}</td><td className="p-3 font-semibold">{r.account_name||'-'}</td><td className="p-3 font-mono">{r.entry_no||'-'}</td><td className="p-3"><b>{r.user_name||'-'}</b><div className="text-xs text-slate-400">{r.user_role||''}</div></td><td className="p-3"><span className="px-2 py-1 rounded-full text-xs font-bold bg-blue-50 text-blue-700">{r.action}</span></td><td className="p-3">{r.module_name||'-'}</td><td className="p-3">{String(r.transaction_date||'').slice(0,10)}</td><td className="p-3 font-mono">{String(r.transaction_time||'').slice(0,8)}</td></tr>)}</tbody></table></div></div></div>
}
